#!name=中国联通
#!date=2026-10-01
#!repo=https://github.com/ning1168/vps

# ───────────── MITM 主机名 ─────────────
# 需要读取请求头 Cookie，故需要 MITM
hostname = loginxx.10010.com, m.client.10010.com, mxx.client.10010.com

# ───────────── 规则 ─────────────
# 抓取登录态 Cookie，进剩余话费/剩余流量页触发通知
^https?:\/\/(loginxx|m|mxx)\.client\.10010\.com\/ url script-request-header https://fastly.jsdelivr.net/gh/ning1168/vps@v1.0.5/js/liantong_cookie.js
^https?:\/\/loginxx\.10010\.com\/ url script-request-header https://fastly.jsdelivr.net/gh/ning1168/vps@v1.0.5/js/liantong_cookie.js
